# ruff.toml
# Unified config for Ruff: linting + formatting (Black style)

# Paths
include = ["*.py", "*.pyi", "**/pyproject.toml"]
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  ".venv",
  "venv",
]

# Formatting (Black-compatible)
line-length = 88
fix = true

[format]
quote-style = "double"        # Use double quotes
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = 88

# Import sorting
[isort]
combine-as-imports = true

# Per-file ignores
[per-file-ignores]
"__init__.py" = ["F401"]      # Ignore unused imports in __init__.py
